
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 06 12:32:31 EST 2017
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REP = 36;
  public static final int PD = 21;
  public static final int EXCLAM = 10;
  public static final int LPAREN = 3;
  public static final int INT = 37;
  public static final int RENDER = 30;
  public static final int MINUS = 12;
  public static final int RPAREN = 4;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int LT = 24;
  public static final int OR = 28;
  public static final int COMMA = 7;
  public static final int DIV = 14;
  public static final int PLUS = 11;
  public static final int ID = 39;
  public static final int FRACTAL = 2;
  public static final int LEFT = 16;
  public static final int EOF = 0;
  public static final int EQUAL = 26;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int SELF = 33;
  public static final int HOME = 22;
  public static final int MOD = 15;
  public static final int REAL = 38;
  public static final int COLON = 8;
  public static final int LBRACE = 5;
  public static final int SAVE = 31;
  public static final int FWD = 18;
  public static final int CLEAR = 23;
  public static final int RBRACE = 6;
  public static final int END = 34;
  public static final int DEF = 35;
  public static final int AT = 9;
  public static final int BACK = 19;
  public static final int RIGHT = 17;
  public static final int RESTORE = 32;
  public static final int GT = 25;
  public static final int PU = 20;
}

